name: Trigger Vercel Deploy

on:
  push:
    branches:
      - main   # Change to 'master' if your branch is still master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Vercel Deploy Hook
        run: curl -X POST $VERCEL_DEPLOY_HOOK
        env:
          VERCEL_DEPLOY_HOOK: ${{ secrets.VERCEL_DEPLOY_HOOK }}
